jobs:
  create_github_release:
    env:
      TAG_NAME: ${{ github.ref }}
    name: Create Github Release
    needs: deploy
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set TAG_NAME without ref
      run: echo "TAG_NAME_WITHOUT_REF=${TAG_NAME//refs\/tags\/}" >> $GITHUB_ENV
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Generate documentation (docbook, html, zip)
      run: ./mvnw asciidoctor:process-asciidoc@output-docbook generate-resources -pl
        chaos-monkey-docs
    - continue-on-error: true
      name: Convert changelog from docbook to markdown
      uses: docker://pandoc/core:3.1
      with:
        args: -f docbook -t gfm -o changes.md chaos-monkey-docs/target/generated-docbook/changes.xml
          --wrap=none
    - continue-on-error: true
      name: Generate jar with dependencies
      run: ./mvnw package -pl chaos-monkey-spring-boot
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: Create Github Release
      uses: softprops/action-gh-release@v2
      with:
        body_path: changes.md
        files: './chaos-monkey-docs/target/chaos-monkey-docs-*.zip

          ./chaos-monkey-spring-boot/target/chaos-monkey-spring-boot-*-jar-with-dependencies.jar

          '
  deploy:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
        java-version: 17
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      env:
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        SONATYPE_USERTOKEN: ${{ secrets.SONATYPE_USERTOKEN }}
        SONATYPE_USERTOKENPASSWORD: ${{ secrets.SONATYPE_USERTOKENPASSWORD }}
      name: Run Maven deploy
      run: ./mvnw deploy -DperformRelease=true --settings .settings.xml -pl chaos-monkey-spring-boot
    - continue-on-error: true
      name: Generate docs
      run: ./mvnw generate-resources -pl chaos-monkey-docs
    - continue-on-error: true
      name: Gather docs
      run: 'mkdir ./docs/latest

        cp -R ./chaos-monkey-docs/target/generated-docs/. ./docs/latest/

        cp README.md ./docs/

        sed -i ''s/docs\/images/images/g'' ./docs/README.md

        '
    - continue-on-error: true
      name: Publish gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        commit_message: ${{ github.event.head_commit.message }}
        enable_jekyll: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
name: Publish Release
on:
  repository_dispatch:
    types: trigger-ga___releasetag.yml
