jobs:
  stale:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        any-of-labels: waiting-for-feedback
        days-before-close: 14
        days-before-stale: 60
        stale-issue-message: This issue was marked as stale because it has been open
          and waiting for feedback for 60 days with no activity. If no feedback is
          provided within 14 days, this will be closed.
name: Close stale issues
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
